name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_PAT_TOKEN }}
        gist_id: 51c8c85804e98a02dd0271e3a857a313
        file_path: resume.json

    - name: Update GitHub Profile About Section
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIST_URL: "https://gist.github.com/malachi43/51c8c85804e98a02dd0271e3a857a313"
        run: |
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user \
            -d "{\"bio\": \"resume_url: $GIST_URL\"}"